CREATE TABLE COUNTRIES_CURRENCIES_REPORT (
  COUNTRY_NAME VARCHAR2(50) NOT NULL,
  COUNTRY_CODE VARCHAR2(2) NOT NULL,
  GMT NUMBER(2) NULL,
  CURRENCY_NAME VARCHAR2(20) NULL,
  CURRENCY_CODE VARCHAR2(3) NULL,
  ITALIAN_TIME TIMESTAMP NOT NULL,
  LOCAL_TIME TIMESTAMP
);

CREATE INDEX COUNTRIES_CURRENCIES_REPORT_DATE_INDEX
ON COUNTRIES_CURRENCIES_REPORT (ITALIAN_TIME);

CREATE INDEX COUNTRIES_CURRENCIES_REPORT_COUNTRY_DATE_INDEX
ON COUNTRIES_CURRENCIES_REPORT (COUNTRY_NAME,ITALIAN_TIME);